name: Lint and Test on Merge
'on':
  push:
    branches:
      - main
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Download Deps 🔧
        run: npm i

      - name: Lint 🚨
        run: npm run lint

      - name: Test ✅
        run: npm run test
