name: Lint and Test on PR
'on': pull_request
jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Download Deps 🔧
        run: npm i

      - name: Lint 🚨
        run: npm run lint

      - name: Test ✅
        run: npm run test
