name: Deploy Typedocs to Github Pages on PR
on: pull_request
permissions:
  contents: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Dependencies and Build Typedocs
        run: npm i --legacy-peer-deps && npm run typedocs:api

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/api
