name: Deploy Typedocs to Github Pages on Merge
'on':
  push:
    branches:
      - main
      - master
permissions:
  contents: write
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Download Deps and Build Typedocs 🔧
        run: npm i && npm run typedocs:api

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/api
